### ISSUE TITLE
SiliconCompiler plug

### ISSUE THREAD

**Issue by aolofsson** [hpretl/iic-osic#1]
Nie effort!

You might be interesged in the siliconcompiler project....itsupports skywater/openroad and a lot of other processes and eda flows.

https://github.com/siliconcompiler/siliconcompiler

**Comment by hpretl** [comment]
Thanks for the comment! I have included `siliconcompiler` into our Docker distribution (see here https://github.com/hpretl/iic-osic-tools), but it is not tested yet.
